export const userDB = [
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },

     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
     {
          nom: "RANDRIANANTENAINA",
          prenom: "Jean Jacques Augustin",
          email: "rjja@outlook.fr",
          type: "user",
     },
];
